version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14
    container_name: newsdb
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsuser -d newsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # News Scraper API
  api:
    build: .
    container_name: news-scraper-api
    environment:
      DATABASE_URL: postgresql://newsuser:newspass@db:5432/newsdb
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DEBUG: "false"
      LOG_LEVEL: INFO
      LOG_FORMAT: json
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        # Wait for database to be ready
        sleep 10 &&
        # Run migrations
        alembic upgrade head &&
        # Start the application
        python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development Database Admin (optional)
  adminer:
    image: adminer
    container_name: news-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data: